import type { Recipe } from '@/context/RecipeContext';

export const LOCAL_RECIPES: Recipe[] = [
  {
    id: 'local-001',
    title: 'Spaghetti Carbonara',
    publisher: 'Italian Kitchen',
    sourceUrl: 'https://www.seriouseats.com/the-best-spaghetti-alla-carbonara-recipe',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80',
    servings: 4,
    cookingTime: 30,
    ingredients: [
      { quantity: 400, unit: 'g', description: 'spaghetti' },
      { quantity: 200, unit: 'g', description: 'pancetta or guanciale' },
      { quantity: 4, unit: '', description: 'large eggs' },
      { quantity: 100, unit: 'g', description: 'Pecorino Romano, grated' },
      { quantity: 2, unit: 'cloves', description: 'garlic' },
      { quantity: null, unit: '', description: 'black pepper to taste' },
    ],
  },
  {
    id: 'local-002',
    title: 'Chicken Tikka Masala',
    publisher: 'Spice Route',
    sourceUrl: 'https://www.bonappetit.com/recipe/chicken-tikka-masala',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    servings: 4,
    cookingTime: 50,
    ingredients: [
      { quantity: 700, unit: 'g', description: 'chicken breast, cubed' },
      { quantity: 400, unit: 'ml', description: 'coconut cream' },
      { quantity: 400, unit: 'g', description: 'canned crushed tomatoes' },
      { quantity: 1, unit: '', description: 'large onion, diced' },
      { quantity: 3, unit: 'cloves', description: 'garlic' },
      { quantity: 2, unit: 'tbsp', description: 'garam masala' },
      { quantity: 1, unit: 'tbsp', description: 'turmeric' },
      { quantity: 2, unit: 'tbsp', description: 'vegetable oil' },
    ],
  },
  {
    id: 'local-003',
    title: 'Classic Beef Burger',
    publisher: 'Grill Masters',
    sourceUrl: 'https://www.seriouseats.com/the-best-burger-recipe',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    servings: 4,
    cookingTime: 20,
    ingredients: [
      { quantity: 600, unit: 'g', description: 'ground beef (80/20)' },
      { quantity: 4, unit: '', description: 'brioche burger buns' },
      { quantity: 4, unit: 'slices', description: 'cheddar cheese' },
      { quantity: 1, unit: '', description: 'large tomato, sliced' },
      { quantity: 1, unit: '', description: 'red onion, sliced' },
      { quantity: null, unit: '', description: 'lettuce leaves' },
      { quantity: 2, unit: 'tbsp', description: 'mayonnaise' },
      { quantity: 1, unit: 'tbsp', description: 'Dijon mustard' },
    ],
  },
  {
    id: 'local-004',
    title: 'Caesar Salad',
    publisher: 'Fresh Table',
    sourceUrl: 'https://www.seriouseats.com/classic-caesar-salad',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    servings: 2,
    cookingTime: 15,
    ingredients: [
      { quantity: 1, unit: 'head', description: 'romaine lettuce' },
      { quantity: 50, unit: 'g', description: 'Parmesan, shaved' },
      { quantity: 100, unit: 'g', description: 'croutons' },
      { quantity: 3, unit: 'tbsp', description: 'Caesar dressing' },
      { quantity: 1, unit: 'clove', description: 'garlic' },
      { quantity: 1, unit: 'tsp', description: 'lemon juice' },
    ],
  },
  {
    id: 'local-005',
    title: 'Beef Tacos',
    publisher: 'Casa Mexican',
    sourceUrl: 'https://www.seriouseats.com/best-ground-beef-tacos',
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&q=80',
    servings: 4,
    cookingTime: 25,
    ingredients: [
      { quantity: 500, unit: 'g', description: 'ground beef' },
      { quantity: 8, unit: '', description: 'corn tortillas' },
      { quantity: 1, unit: '', description: 'onion, diced' },
      { quantity: 2, unit: 'cloves', description: 'garlic' },
      { quantity: 2, unit: 'tsp', description: 'cumin' },
      { quantity: 1, unit: 'tsp', description: 'chili powder' },
      { quantity: 100, unit: 'g', description: 'cheddar cheese, shredded' },
      { quantity: null, unit: '', description: 'fresh cilantro and lime to serve' },
    ],
  },
  {
    id: 'local-006',
    title: 'Mushroom Risotto',
    publisher: 'Italian Kitchen',
    sourceUrl: 'https://www.bonappetit.com/recipe/mushroom-risotto',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80',
    servings: 4,
    cookingTime: 40,
    ingredients: [
      { quantity: 320, unit: 'g', description: 'Arborio rice' },
      { quantity: 400, unit: 'g', description: 'mixed mushrooms, sliced' },
      { quantity: 1, unit: 'L', description: 'warm vegetable stock' },
      { quantity: 1, unit: '', description: 'shallot, finely diced' },
      { quantity: 2, unit: 'cloves', description: 'garlic' },
      { quantity: 80, unit: 'ml', description: 'dry white wine' },
      { quantity: 60, unit: 'g', description: 'Parmesan, grated' },
      { quantity: 30, unit: 'g', description: 'butter' },
    ],
  },
  {
    id: 'local-007',
    title: 'Banana Bread',
    publisher: 'Home Bakery',
    sourceUrl: 'https://www.seriouseats.com/the-best-banana-bread-recipe',
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800&q=80',
    servings: 8,
    cookingTime: 70,
    ingredients: [
      { quantity: 3, unit: '', description: 'very ripe bananas' },
      { quantity: 190, unit: 'g', description: 'all-purpose flour' },
      { quantity: 150, unit: 'g', description: 'sugar' },
      { quantity: 2, unit: '', description: 'eggs' },
      { quantity: 115, unit: 'g', description: 'unsalted butter, melted' },
      { quantity: 1, unit: 'tsp', description: 'baking soda' },
      { quantity: 0.5, unit: 'tsp', description: 'salt' },
      { quantity: 1, unit: 'tsp', description: 'vanilla extract' },
    ],
  },
  {
    id: 'local-008',
    title: 'Chocolate Chip Cookies',
    publisher: 'Sweet Treats',
    sourceUrl: 'https://www.seriouseats.com/the-food-lab-best-chocolate-chip-cookies',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80',
    servings: 24,
    cookingTime: 35,
    ingredients: [
      { quantity: 225, unit: 'g', description: 'unsalted butter' },
      { quantity: 200, unit: 'g', description: 'brown sugar' },
      { quantity: 100, unit: 'g', description: 'white sugar' },
      { quantity: 2, unit: '', description: 'eggs' },
      { quantity: 2, unit: 'tsp', description: 'vanilla extract' },
      { quantity: 280, unit: 'g', description: 'all-purpose flour' },
      { quantity: 1, unit: 'tsp', description: 'baking soda' },
      { quantity: 300, unit: 'g', description: 'dark chocolate chips' },
    ],
  },
  {
    id: 'local-009',
    title: 'French Onion Soup',
    publisher: 'Bistro Classique',
    sourceUrl: 'https://www.seriouseats.com/french-onion-soup-recipe',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    servings: 4,
    cookingTime: 90,
    ingredients: [
      { quantity: 1, unit: 'kg', description: 'yellow onions, thinly sliced' },
      { quantity: 60, unit: 'g', description: 'unsalted butter' },
      { quantity: 1, unit: 'L', description: 'beef stock' },
      { quantity: 150, unit: 'ml', description: 'dry white wine' },
      { quantity: 4, unit: 'slices', description: 'baguette, toasted' },
      { quantity: 150, unit: 'g', description: 'Gruyère cheese, grated' },
      { quantity: 1, unit: 'tbsp', description: 'fresh thyme' },
    ],
  },
  {
    id: 'local-010',
    title: 'Guacamole',
    publisher: 'Casa Mexican',
    sourceUrl: 'https://www.seriouseats.com/the-best-guacamole',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&q=80',
    servings: 4,
    cookingTime: 10,
    ingredients: [
      { quantity: 3, unit: '', description: 'ripe avocados' },
      { quantity: 1, unit: '', description: 'lime, juiced' },
      { quantity: 0.5, unit: '', description: 'red onion, finely diced' },
      { quantity: 1, unit: '', description: 'jalapeño, seeded and minced' },
      { quantity: 2, unit: 'tbsp', description: 'fresh cilantro, chopped' },
      { quantity: 1, unit: 'clove', description: 'garlic, minced' },
      { quantity: 0.5, unit: 'tsp', description: 'salt' },
    ],
  },
  {
    id: 'local-011',
    title: 'Grilled Salmon',
    publisher: 'Nordic Table',
    sourceUrl: 'https://www.seriouseats.com/pan-seared-salmon-recipe',
    image: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=800&q=80',
    servings: 2,
    cookingTime: 15,
    ingredients: [
      { quantity: 2, unit: '', description: 'salmon fillets (200g each)' },
      { quantity: 2, unit: 'tbsp', description: 'olive oil' },
      { quantity: 1, unit: '', description: 'lemon, juiced and zested' },
      { quantity: 2, unit: 'cloves', description: 'garlic, minced' },
      { quantity: 1, unit: 'tbsp', description: 'fresh dill' },
      { quantity: null, unit: '', description: 'salt and black pepper to taste' },
    ],
  },
  {
    id: 'local-012',
    title: 'Greek Salad',
    publisher: 'Mediterranean Kitchen',
    sourceUrl: 'https://www.seriouseats.com/greek-salad-recipe',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    servings: 4,
    cookingTime: 10,
    ingredients: [
      { quantity: 4, unit: '', description: 'ripe tomatoes, chopped' },
      { quantity: 1, unit: '', description: 'English cucumber, chopped' },
      { quantity: 1, unit: '', description: 'green bell pepper, sliced' },
      { quantity: 0.5, unit: '', description: 'red onion, sliced' },
      { quantity: 200, unit: 'g', description: 'feta cheese, cubed' },
      { quantity: 80, unit: 'g', description: 'Kalamata olives' },
      { quantity: 3, unit: 'tbsp', description: 'extra virgin olive oil' },
      { quantity: 1, unit: 'tsp', description: 'dried oregano' },
    ],
  },
];
